### PR TITLE
Update models.py

### PR DESCRIPTION
**Pull request by devanshanker**
Added a variable in named 'suspend' which holds a boolean value depending on whether or not the boolean is suspended.

### CODE REVIEW

**Review by dymontg — CHANGES_REQUESTED** [review]
Nice! Did you makemigrations? Can you add a test?

**Comment by dymontg** [comment]
I'm going to reject this PR as you are trying to merge into jwt which has an open PR #9. Please try to merge into devel.

**Comment by devanshanker** [comment]
How do I approve your changes?

**Comment by dymontg** [comment]
@devanshanker I've make the migrations. However, since this was checked out of jwt which hasn't been merged, I have to close this PR. It can be reopened once #9 is accepted.

**Comment by dymontg** [comment]
Reopened as JWT was merged into devel.

**Review by dymontg — APPROVED** [review]

**Pull request merged**
