### PR TITLE
Update auth serializers

### PR DESCRIPTION
**Pull request by dymontg**
#### Short description of what this pull request does:
Refactors auth app serialization

#### Changes proposed in this pull request:

- Refactor `UserSerializer`
- Refactor `UserProfileSerializer`

### CODE REVIEW

**Comment by devanshanker** [comment]
I'll take a look before lunch.

**Review by devanshanker — APPROVED** [review]
Can you explain why you replaced create(...) and update(...)? (I don't think it's wrong, I just don't know the benefits.) 
Minor note: If we are using school ID numbers, it might be easiest for usernames to be 6 digits.

**Comment by dymontg** [comment]
I sought to rewrite .create() and .update() to clean up the code. It was more of a refactor.

**Comment by devanshanker** [comment]
So neither of them are standard Django/REST methods?

**Comment by dymontg** [comment]
Well A serializer converts python objects into `BaseSerializer` objects and the .create() and .update() methods are methods that can be overwritten to change behaviour when making a POST, PUT, or PATCH request or when saving the objects pragmatically.

**Comment by devanshanker** [comment]
You answered my badly written question – thanks!

**Pull request merged**
